spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev?useSSL=false
    username: sfg_dev_user
    password: guru
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false

